version: '3'

services:

  db:
    image: neo4j:latest
    env_file:
      - '.env'
    ports:
      - '7474:7474'
      - '7687:7687'
    volumes:
      - 'db:/data'

  testdb:
    image: neo4j:latest
    env_file:
      - '.env'
      - '.testenv'
    ports:
      - '7475:7475'
      - '7688:7688'
    volumes:
      - 'testdb:/data'
        
  web:
    build: '.'
    depends_on:
      - 'db'
      - 'testdb'
    env_file:
      - '.env'
    ports: 
      - '5000:5000'
    volumes:
      - '.:/app'
    links:
      - 'db:db'
      - 'testdb:testdb'

volumes:
  db:
  testdb:
